### ISSUE TITLE
mvn install fails in blinky-diagnostics 

### ISSUE THREAD

**Issue by jycamus90** [spideruci/blinky#10]
```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1.1:exec (default) on project blinky-diagnostics: Result of /bin/sh -c cd /Users/Ku/Documents/uci/research/blinky/blinky-diagnostics && /Users/Ku/Documents/uci/research/blinky/blinky-diagnostics/scripts/diagnose execution is: '1'. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1.1:exec (default) on project blinky-diagnostics: Result of /bin/sh -c cd /Users/Ku/Documents/uci/research/blinky/blinky-diagnostics && /Users/Ku/Documents/uci/research/blinky/blinky-diagnostics/scripts/diagnose execution is: '1'.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Result of /bin/sh -c cd /Users/Ku/Documents/uci/research/blinky/blinky-diagnostics && /Users/Ku/Documents/uci/research/blinky/blinky-diagnostics/scripts/diagnose execution is: '1'.
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:283)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Any idea? mvn install fails only in blinky-diagnostics

**Comment by jycamus90** [comment]
Okay I saw the issue below.

**Comment by VijayKrishna** [comment]
so what was the issue?

**Comment by jycamus90** [comment]
mvn install fails on blinky-diagnostics because there were exceptions in TheOne and NoCommitment as described in issue #8.

**Comment by VijayKrishna** [comment]
@jycamus90 confirm if it now passes/fails. I just pulled @CharlesFengY's PR #9 into master and that should have  fixed this issue. if it passes, go ahead and close the issue.
