### ISSUE TITLE
Subjects (TheOne and NoCommitment) not working

### ISSUE THREAD

**Issue by VijayKrishna** [spideruci/blinky#8]
Following subjects not working in blinky-diagnostics:
- [x] styleEx.TheOne
- [x] styleEx.noCommitment.NoCommitment

steps to reproduce:
- pull the repo...
- run `mvn test` to ensure that the code compiles and executes all the junit tests
- run `mvn verify`
- assuming that the code compiles and executes all the junit tests, the following error message should appear at the end of the run:

```
[INFO] styleEx.TheOne
[INFO] 🏃 running styleEx.TheOne with java
[INFO] Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
[INFO] 	at org.spideruci.analysis.diagnostics.subjects.styleEx.TheOne.main(TheOne.java:141)
```

```
[INFO] styleEx.noCommitment.NoCommitment
[INFO] 🏃 running styleEx.noCommitment.NoCommitment with java
[INFO] Exception in thread "main" java.lang.NullPointerException
[INFO] 	at org.spideruci.analysis.diagnostics.subjects.styleEx.noCommitment.NoCommitment.load_plugins(NoCommitment.java:27)
[INFO] 	at org.spideruci.analysis.diagnostics.subjects.styleEx.noCommitment.NoCommitment.main(NoCommitment.java:38)
```

**Comment by VijayKrishna** [comment]
#9 fixed the issue.
